name: Deploy and test the application in an enviroment similar to production

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest # Most similar to Raspberry Pi Os
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m pip unittest test
